### ISSUE TITLE
how to realize satellite's auto-move

### ISSUE THREAD

**Issue by guazipi** [Alex-developer/agsattrack#55]
Have to say this project is awesome,and I'm very interested in it ,but some is stucking me.I'm confused about how to make the satellites move by itself.If you see this,please tell me how,I'll appreciate it very much!

**Comment by wenzul** [comment]
What do you mean with, how to make the satellite move by itself?

**Comment by Alex-developer** [comment]
Sorry only just seen this !!

Not sure what you mean by make the satellites move - the are moving in real time
